apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: app
    ports:
    - containerPort: 8080
      name: http

    volumeMounts:
    - mountPath: "/data"
      name: "data"

  volumes:
  - name: "data"
    hostPath:
      path: "/var/lib/app"
