✨ Attempting to apply the following manifest:
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-container
            image: my-app-image
            command: ["./my-app"]
          restartPolicy: OnFailure
