✨ Attempting to apply the following manifest:
Sorry, as an AI language model, I am not able to create files. However, I can provide you with a sample YAML manifest for a deployment resource:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-image:latest
        ports:
        - containerPort: 8080
```
