apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - image: gcr.io/tidy-cortex-389712/server-v1
    name: app
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
