✨ Attempting to apply the following manifest:
apiVersion: v1
kind: Pod
metadata:
  name: app-liveness-probe
spec:
  containers:
  - name: app-container
    image: my-app-image
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
