✨ Attempting to apply the following manifest:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-multicontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-multicontainer
  template:
    metadata:
      labels:
        app: app-multicontainer
    spec:
      containers:
      - name: app-container-1
        image: nginx
        ports:
        - containerPort: 80
      - name: app-container-2
        image: busybox
        command: ['sh', '-c', 'echo Hello from the second container! && sleep 3600']
      - name: app-container-3
        image: redis
        env:
        - name: REDIS_PASSWORD
          value: "password123"
        ports:
        - containerPort: 6379
      restartPolicy: Always
