apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
  - name: my-app-container
    image: my-app-image
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: my-app-secret
          key: secret-key
