apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
    run: app
spec:
  containers:
  - name: app
    image: gcr.io/tidy-cortex-389712/server-v1
    ports:
    - containerPort: 80
      name: http
