✨ Attempting to apply the following manifest:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        run: app
    spec:
      containers:
      - name: app
        image: gcr.io/k8s-k3s/demo:v1.0.0
        ports:
        - containerPort: 80
